### ISSUE TITLE
Feature Request - Limit Scope

### ISSUE THREAD

**Issue by RRRII** [cloudfoundry-community/cron-boshrelease#7]
Just wanted to see if there was a way that we can limit the servers that the cron job is placed on.  For example if a job or instance group inside of the deployment manifest has more than one server that gets deployed with it and the cron entry only needs to be put on one server,   Something similar to below:
```
instance_groups:
- name: instancegroup
  instances: 2
  azs: [z1, z2]
  networks: 
  - name: default
  - static_ips: [x.x.x.x, y.y.y.y]
  vm_type: default
  stemcell: default
  persistent_disk: 10000
  jobs:
  - name: job-1
    release: release-1
  - name: cron
  - release: cron
  properties:
    cron:
      include:
      - static_ips: y.y.y.y
      entries:
      - command: etc
```
